services:
  # Monolithic Service (Frontend + Backend)
  - type: web
    name: me-api-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
